CREATE TABLE [dbo].[StoreUser] (
    [StoreUserID]          INT             IDENTITY (1000, 1) NOT NULL,
    [FirstName]            NVARCHAR (100)  NOT NULL,
    [LastName]             NVARCHAR (100)  NULL,
    [Email]                NVARCHAR (255)  NOT NULL,
    [Password]             NVARCHAR (MAX)  NULL,
    [GroupId]              INT             NOT NULL,
    [Mobile]               NVARCHAR (13)   NULL,
    [Status]               INT             DEFAULT ((1)) NULL,
    [Guid]                 NVARCHAR (500)  NULL,
    [GuidTimeStamp]        DATETIME        NULL,
    [IsGuidExpired]        BIT             DEFAULT ((0)) NULL,
    [LoginTimeStamp]       DATETIME        NULL,
    [IpAddress]            NVARCHAR (20)   NULL,
    [CreatedAT]            DATETIME        DEFAULT (getdate()) NULL,
    [UpdatedAT]            DATETIME        NULL,
    [IsDeleted]            BIT             DEFAULT ((0)) NULL,
    [ForceUpdatePassword]  BIT             DEFAULT ((0)) NULL,
    [LastModifiedPassword] DATETIME        DEFAULT (getdate()) NULL,
    [WrongLoginAttempt]    INT             DEFAULT ((0)) NULL,
    [LoginAttemptTime]     DATETIME        NULL,
    [Is2FAEnabled]         BIT             DEFAULT ((0)) NULL,
    [IsOTPEnabled]         BIT             DEFAULT ((0)) NULL,
    [ImagePath]            NVARCHAR (4000) NULL,
    [OTP]                  NVARCHAR (10)   NULL,
    [OTPTimeStamp]         DATETIME        DEFAULT (getdate()) NULL,
    [SecretKey2FA]         NVARCHAR (255)  NULL,
    [TimeStamp2FA]         DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([StoreUserID] ASC),
    UNIQUE NONCLUSTERED ([Email] ASC)
);

